apiVersion: v1
kind: Service
metadata:
  name: shelly
  namespace: fluidomos-datacenter
spec:
  ports:
    - protocol: TCP
      port: 50003
      targetPort: 50003
  selector:
    app: pydelis-shelly
