apiVersion: v1
kind: Service
metadata:
  name: wc
  namespace: fluidomos-datacenter
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  externalIPs:
    - 10.255.0.131
  selector:
    app: wc
