apiVersion: v1
kind: Service
metadata:
  name: cable
  namespace: fluidomos-datacenter
spec:
  ports:
    - protocol: TCP
      port: 28080
      targetPort: 28080
  externalIPs:
    - 10.255.0.131
  selector:
    app: cable
